# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_artical_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField()),
                ('text', models.CharField(max_length=300)),
                ('like', models.IntegerField()),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Artical')),
            ],
        ),
    ]
