# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='tag',
            field=models.CharField(default=b'lifestyle', max_length=15),
        ),
    ]
