# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20170902_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='img_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
