# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20170902_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artical',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artical',
            name='img_url',
            field=models.CharField(max_length=100),
        ),
    ]
