# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20170907_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stag',
            name='artical',
            field=models.ManyToManyField(blank=True, null=True, to='myblog.Artical'),
        ),
    ]
