# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_auto_20170907_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stag',
            name='articals',
            field=models.ManyToManyField(to='myblog.Artical'),
        ),
    ]
